import { PublicationFigure } from '../components/charts/PublicationFigure'
import { ResearchTimeSeriesChart } from '../components/charts/ResearchTimeSeriesChart'
import { EvidenceLabel } from '../components/EvidenceLabel'
import { PageBody, PageHeader } from '../components/PageHeader'
import { ResearchText } from '../components/ResearchText'
import { researchData } from '../data/generated'

export function EnergyBurden() {
  const rows = researchData.systemResponse.burdenValidation
  return <><PageHeader eyebrow="Affordability layer" title="Energy cost relative to economic capacity" description="Nominal oil prices are only one part of stress. Burden measures ask how energy costs compare with household income, real prices, and economic output." /><PageBody><div className="flex flex-wrap gap-2"><EvidenceLabel label="Experimental proxy" /><EvidenceLabel label="Contextual indicator" /></div><div className="mt-6 max-w-4xl"><ResearchText text={researchData.systemResponse.content.burdenResult} /><ResearchText text={researchData.systemResponse.content.burdenInterpretation} /></div><div className="mt-8"><ResearchTimeSeriesChart file="energy-burden.json" initialTransformation="zscore" inspectCrossLayer /></div><section className="mt-12"><h2 className="text-xl font-semibold">Transmission into activity</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600 dark:text-stone-300">The interactive history places energy burden beside production, manufacturing, spending, investment, and GDP. Co-movement remains distinct from out-of-sample usefulness.</p><div className="mt-5"><ResearchTimeSeriesChart file="industrial-transmission.json" initialTransformation="zscore" syncUrl={false} /></div></section><div className="mt-10 overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead><tr className="border-b border-stone-300 dark:border-stone-700"><th className="py-3">Validation</th><th>Model</th><th>Predictions</th><th>RMSE</th><th>MAE</th><th>R²</th><th>vs AR</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.validation}-${row.model}`} className="border-b border-stone-200 dark:border-stone-800"><td className="py-3">{row.validation}</td><td>{row.model}</td><td>{row.n_predictions}</td><td>{row.rmse?.toFixed(2) ?? '—'}</td><td>{row.mae?.toFixed(2) ?? '—'}</td><td>{row.r2?.toFixed(2) ?? '—'}</td><td>{row.rmse_improvement_vs_ar === null ? '—' : `${(row.rmse_improvement_vs_ar * 100).toFixed(1)}%`}</td></tr>)}</tbody></table></div><div className="mt-12 space-y-6"><PublicationFigure src="/charts/energy_burden_dashboard.png" alt="Real oil and energy expenditure burden over time" title="Energy-burden dashboard" description="Price, income, and expenditure measures are displayed separately to preserve conflicting evidence." source="EIA WTI; BEA energy expenditures, disposable income and GDP; BLS CPI via FRED." /><PublicationFigure src="/charts/industrial_transmission.png" alt="Energy burden and industrial output transmission" title="Industrial transmission" description="Historical co-movement is visible, but first-pass out-of-sample improvement is not stable." source="BEA energy burden and Federal Reserve industrial production; latest-vintage observations." /></div></PageBody></>
}
