import { PublicationFigure } from '../components/charts/PublicationFigure'
import { ResearchTimeSeriesChart } from '../components/charts/ResearchTimeSeriesChart'
import { EvidenceLabel } from '../components/EvidenceLabel'
import { PageBody, PageHeader } from '../components/PageHeader'
import { ResearchText } from '../components/ResearchText'
import { researchData } from '../data/generated'

export function Labour() {
  const rows = researchData.systemResponse.labourWarnings
  return <><PageHeader eyebrow="Early consequences" title="Hours and employment quality before headline layoffs" description="The first pass tests whether hours, temporary help, and real wages reveal strain earlier than headline unemployment." /><PageBody><div className="max-w-4xl"><ResearchText text={researchData.systemResponse.content.labourHypothesis} /><ResearchText text={researchData.systemResponse.content.labourMethod} /></div><div className="mt-8"><ResearchTimeSeriesChart file="labour-warning.json" initialSeries={['average_weekly_hours_YoY', 'temporary_help_YoY', 'real_wage_growth', 'unemployment_rate']} initialTransformation="zscore" inspectCrossLayer /></div><div className="mt-8 grid gap-4 md:grid-cols-2">{rows.map((row) => <article key={row.indicator} className="border border-stone-200 bg-white p-5 dark:border-stone-800 dark:bg-[#18201d]"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{row.indicator.replaceAll('_', ' ')}</h2><EvidenceLabel label={row.evidence_label} /></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-stone-500">Lead to recession</dt><dd className="mt-1 font-semibold">{row.best_lead_months_to_recession} months</dd></div><div><dt className="text-stone-500">Correlation</dt><dd className="mt-1 font-semibold">{row.correlation_with_future_recession?.toFixed(2) ?? '—'}</dd></div><div><dt className="text-stone-500">Lead to industrial weakness</dt><dd className="mt-1 font-semibold">{row.best_lead_months_to_industrial_weakness} months</dd></div><div><dt className="text-stone-500">Correlation</dt><dd className="mt-1 font-semibold">{row.correlation_with_future_industrial_weakness?.toFixed(2) ?? '—'}</dd></div></dl></article>)}</div><div className="mt-12 space-y-6"><PublicationFigure src="/charts/labour_early_warning_indicators.png" alt="Weekly hours temporary-help employment real wages and unemployment" title="Labour early-warning indicators" description="Flexible margins can move before payroll counts, but timing remains episode-dependent." source="BLS labour series via FRED; shaded periods use the NBER recession indicator." /><PublicationFigure src="/charts/household_stress_indicators.png" alt="Consumer sentiment delinquency and real income indicators" title="Household stress context" description="Household evidence helps confirm or contradict labour and affordability symptoms." source="BEA, Federal Reserve, University of Michigan and BLS series via FRED." /></div></PageBody></>
}
