import { PublicationFigure } from '../components/charts/PublicationFigure'
import { ResearchTimeSeriesChart } from '../components/charts/ResearchTimeSeriesChart'
import { FrameworkStatusNotice } from '../components/FrameworkStatusNotice'
import { PageBody, PageHeader } from '../components/PageHeader'
import { ResearchText } from '../components/ResearchText'
import { researchData } from '../data/generated'

export function Regimes() {
  return <><PageHeader eyebrow="Historical framework" title="Regime framework and historical sequences" description="Expansion, tightening, affordability stress, demand destruction, collapse, and recovery are states to test against evidence, not automatic descriptions of today." /><PageBody><FrameworkStatusNotice subject="regime" /><section className="mt-10"><p className="text-xs font-semibold uppercase text-petroleum">Framework states</p><h2 className="mt-2 text-2xl font-semibold">How a system can move through stress and recovery</h2><div className="mt-4 max-w-4xl"><ResearchText text={researchData.systemResponse.content.regimes} /></div></section><section className="mt-10"><p className="text-xs font-semibold uppercase text-petroleum">Historical diagnostic</p><h2 className="mt-2 text-2xl font-semibold">Demand-destruction patterns across past observations</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600 dark:text-stone-300">This chart supports comparison with earlier episodes. Shading and event markers identify historical windows; they do not declare the current regime.</p><div className="mt-6"><ResearchTimeSeriesChart file="demand-destruction.json" initialTransformation="zscore" inspectCrossLayer /></div></section><div className="mt-12 space-y-6"><PublicationFigure src="/charts/regime_timeline.png" alt="Timeline of historical energy and economic regimes" title="Historical regime timeline" description="Episode boundaries provide comparison windows; they are not an automatic current-state classifier." source="Project-defined historical episodes using EIA, FRED, BEA and BLS observations." /><PublicationFigure src="/charts/demand_destruction_cycle.png" alt="Demand destruction sequence around oil price peaks" title="Demand destruction cycle" description="A falling oil price can be part of worsening conditions when activity and demand are contracting." source="WTI, petroleum consumption, industrial production and NBER recession periods." /></div></PageBody></>
}
