import { EvidenceLabel } from '../components/EvidenceLabel'
import { PageBody, PageHeader } from '../components/PageHeader'

const symptoms = [
  { name: 'Inventories fall while prices rise', meaning: 'Possible physical tightening as demand outruns immediately available supply.', chain: 'Physical tightness → oil price', confirm: 'Production, consumption, refinery utilization, imports and futures structure.', alternatives: 'Weather, logistics, maintenance, exports, seasonal inventory movement.', example: '2007–08 and selected 2021–22 months.', evidence: 'Supported historical pattern' },
  { name: 'Prices fall while unemployment rises', meaning: 'Possible demand destruction or recession rather than improved physical abundance.', chain: 'Demand destruction → price collapse → labour after-effects', confirm: 'Industrial production, consumption, hours, credit and recession indicators.', alternatives: 'Positive supply shock, productivity gain, currency movement.', example: '2008–09 and 2020.', evidence: 'Supported historical pattern' },
  { name: 'Real wages decline despite employment growth', meaning: 'Energy and general inflation may be eroding purchasing power before job counts weaken.', chain: 'Affordability stress → household consequences', confirm: 'Energy CPI, disposable income, hours and consumer sentiment.', alternatives: 'Broader inflation, workforce composition, wage measurement effects.', example: '2021–22.', evidence: 'Contextual indicator' },
  { name: 'Temporary work and weekly hours weaken', meaning: 'Firms may be reducing flexible labour input before broad layoffs.', chain: 'Economic transmission → labour after-effects', confirm: 'Manufacturing, spending, full-time share and unemployment claims.', alternatives: 'Sector rebalancing, regulation, hiring-channel changes.', example: '2001, 2007–09 and 2020.', evidence: 'Supported historical pattern' },
  { name: 'Energy burden rises faster than income', meaning: 'Households and firms may have less room for non-energy spending and investment.', chain: 'Oil price → affordability stress → consumption', confirm: 'Real income, energy CPI, sentiment, delinquency and spending.', alternatives: 'Cold weather, utility regulation, income-composition shifts.', example: '1979–80, 2007–08 and 2022.', evidence: 'Experimental proxy' },
  { name: 'Industrial output weakens after an oil spike', meaning: 'A price shock may be transmitting through costs, margins and demand.', chain: 'Energy burden → industrial production', confirm: 'Manufacturing, petroleum demand, business investment and credit.', alternatives: 'Monetary tightening, financial crisis, external demand shock.', example: 'Multiple episodes, with unstable timing.', evidence: 'Supported historical pattern' },
]

export function Symptoms() {
  return <><PageHeader eyebrow="Symptom guide" title="Observable patterns and what to check next" description="A symptom is a prompt for confirmation, not a diagnosis by itself." /><PageBody><div className="divide-y divide-stone-200 border-y border-stone-200 dark:divide-stone-800 dark:border-stone-800">{symptoms.map((item) => <article key={item.name} className="py-7"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{item.name}</h2><EvidenceLabel label={item.evidence} /></div><p className="mt-3 max-w-4xl leading-7 text-stone-700 dark:text-stone-300">{item.meaning}</p><dl className="mt-5 grid gap-4 text-sm md:grid-cols-2 xl:grid-cols-4"><div><dt className="font-semibold">Transmission link</dt><dd className="mt-1 text-stone-500">{item.chain}</dd></div><div><dt className="font-semibold">Confirm with</dt><dd className="mt-1 text-stone-500">{item.confirm}</dd></div><div><dt className="font-semibold">Alternatives</dt><dd className="mt-1 text-stone-500">{item.alternatives}</dd></div><div><dt className="font-semibold">Examples</dt><dd className="mt-1 text-stone-500">{item.example}</dd></div></dl></article>)}</div></PageBody></>
}
