import { Link } from 'react-router-dom'
import type { CanadianClassification, CanadianClock, RegionalSide } from './canadaTypes'

const pct = (value: number) => `${(100 * value).toFixed(0)}%`
const month = (value: string | null) => value ? new Intl.DateTimeFormat('en-CA', { month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value.slice(0, 10)}T00:00:00Z`)) : 'Unavailable'

function Clock({ title, clock }: { title: string; clock: CanadianClock }) {
  return <article className="border-t-2 border-petroleum pt-4"><p className="text-xs font-semibold uppercase text-stone-500">{title}</p><h3 className="mt-2 text-xl font-semibold">{clock.classification}</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-stone-500">Classification date</dt><dd className="font-medium">{month(clock.classificationDate)}</dd></div><div><dt className="text-stone-500">Confidence</dt><dd className="font-medium capitalize">{clock.confidence}</dd></div><div><dt className="text-stone-500">Indicator availability</dt><dd className="font-medium">{pct(clock.requiredIndicatorAvailability)}</dd></div><div><dt className="text-stone-500">Freshness-adjusted</dt><dd className="font-medium">{pct(clock.freshnessAdjustedCoverage)}</dd></div><div><dt className="text-stone-500">Observation range</dt><dd className="font-medium">{month(clock.oldestRequiredObservationDate)} to {month(clock.newestObservationDate)}</dd></div><div><dt className="text-stone-500">Stale / partial</dt><dd className="font-medium">{clock.staleIndicators.length} / {clock.partialPeriodIndicators.length}</dd></div></dl>{title.startsWith('Quarterly') && <p className="mt-3 text-xs text-amber-700 dark:text-amber-300">Retrospective quarterly-aligned classification using revised data</p>}</article>
}

function Region({ title, side }: { title: string; side: RegionalSide }) {
  return <div className="border-t border-stone-300 pt-4 dark:border-stone-700"><div className="flex items-baseline justify-between gap-4"><h4 className="font-semibold">{title}</h4><span className="text-lg font-semibold">{(100 * side.score).toFixed(1)}%</span></div><p className="mt-1 text-xs text-stone-500">Availability {pct(side.coverage)}</p><ul className="mt-3 space-y-2 text-sm">{side.evidence.slice(0, 3).map((row) => <li key={`${title}-${row.indicator}`}><span className="font-semibold text-emerald-700 dark:text-emerald-300">✓</span> {row.label}</li>)}{side.conflicts.slice(0, 2).map((row) => <li key={`${title}-conflict-${row.indicator}`}><span className="font-semibold text-rose-700 dark:text-rose-300">×</span> {row.label}</li>)}{side.missing.slice(0, 2).map((row) => <li key={`${title}-missing-${row.indicator}`} className="text-stone-500"><span className="font-semibold">~</span> {row.label}</li>)}</ul></div>
}

export function CanadianDiagnosticSummary({ classification, compact = false }: { classification: CanadianClassification; compact?: boolean }) {
  const clock = classification.provisionalClassification
  return <section className="border-y border-stone-300 py-6 dark:border-stone-700"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-petroleum">Canadian diagnostic interpretation · Provisional transparent classifier</p><h2 className="mt-2 text-2xl font-semibold">{classification.status}</h2></div><p className="max-w-md text-xs leading-5 text-stone-500"><strong className="text-ink dark:text-white">Scope:</strong> {classification.scope}</p></div><p className="mt-4 max-w-5xl leading-7 text-stone-700 dark:text-stone-300">{classification.summary}</p><div className={`mt-7 grid gap-7 ${compact ? 'lg:grid-cols-2' : 'xl:grid-cols-2'}`}><Clock title="Provisional monthly Canadian nowcast" clock={clock} /><Clock title="Quarterly-aligned Canadian state" clock={classification.quarterlyAlignedClassification} /></div>
    <div className="mt-7 grid gap-6 lg:grid-cols-2"><Region title="Ontario transmission" side={classification.regionalDivergence.ontarioTransmission} /><Region title="Alberta producer conditions" side={classification.regionalDivergence.albertaProducerConditions} /></div><p className="mt-4 text-sm font-medium">Regional result: {classification.regionalDivergence.status}</p><p className="mt-1 text-xs text-stone-500">{classification.regionalDivergence.explanation}</p>
    <div className="mt-6 flex flex-wrap gap-3 text-sm"><Link className="font-semibold text-petroleum underline underline-offset-4" to="/canada/symptoms">Inspect Canadian symptoms</Link><Link className="font-semibold text-petroleum underline underline-offset-4" to="/canada/regimes">Compare all regime scores</Link></div><p className="mt-5 text-xs leading-5 text-amber-700 dark:text-amber-300">{clock.revisedDataWarning}</p></section>
}
