import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { EvidenceLabel } from '../EvidenceLabel'

type Row = { target: string; model: string; lagMonths: number; windowMonths: number; sample: string; n: number; rmse: number | null; mae: number | null; r2: number | null; directionalAccuracy: number | null; signAccuracy: number | null }

export function RollingModelPerformanceChart() {
  const [rows, setRows] = useState<Row[]>([])
  const [model, setModel] = useState('gm2_only')
  useEffect(() => { void fetch(`${import.meta.env.BASE_URL}generated/rolling-performance.json`).then((response) => response.json()).then((payload) => setRows(payload.rows)) }, [])
  const models = useMemo(() => [...new Set(rows.map((row) => row.model))], [rows])
  const data = rows.filter((row) => row.model === model).sort((a, b) => a.windowMonths - b.windowMonths)
  if (!rows.length) return <div className="h-52 border border-stone-200 p-5 text-sm text-stone-500 dark:border-stone-800">Loading rolling validation…</div>
  return <section className="border-y border-stone-200 py-6 dark:border-stone-800"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">Rolling model performance</h2><EvidenceLabel label="Validated relationship" /></div><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600 dark:text-stone-300">Compare RMSE and MAE for the locked lag across 60-, 84-, and 120-month rolling windows. Lower errors are better; window stability matters more than one in-sample fit.</p></div><select value={model} onChange={(event) => setModel(event.target.value)} className="h-10 border border-stone-300 bg-white px-3 text-sm dark:border-stone-700 dark:bg-[#18201d]">{models.map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></div><div className="mt-5 h-72"><ResponsiveContainer><BarChart data={data}><CartesianGrid opacity={0.55} /><XAxis dataKey="windowMonths" label={{ value: 'Rolling window (months)', position: 'bottom' }} /><YAxis /><Tooltip formatter={(value) => Number(value).toFixed(2)} /><Legend /><Bar dataKey="rmse" name="RMSE" fill="var(--chart-1)" /><Bar dataKey="mae" name="MAE" fill="var(--chart-3)" /></BarChart></ResponsiveContainer></div><details className="mt-4 border-t border-stone-200 pt-4 dark:border-stone-800"><summary className="cursor-pointer text-sm font-semibold">Accessible validation table</summary><div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr><th className="p-2">Window</th><th className="p-2">Predictions</th><th className="p-2">RMSE</th><th className="p-2">MAE</th><th className="p-2">R²</th><th className="p-2">Directional accuracy</th></tr></thead><tbody>{data.map((row) => <tr key={row.windowMonths} className="border-t dark:border-stone-800"><td className="p-2">{row.windowMonths} months</td><td className="p-2">{row.n}</td><td className="p-2">{row.rmse?.toFixed(2) ?? 'n/a'}</td><td className="p-2">{row.mae?.toFixed(2) ?? 'n/a'}</td><td className="p-2">{row.r2?.toFixed(2) ?? 'n/a'}</td><td className="p-2">{row.directionalAccuracy === null ? 'n/a' : `${(row.directionalAccuracy * 100).toFixed(1)}%`}</td></tr>)}</tbody></table></div></details></section>
}
